### ISSUE TITLE
Cache things: Avoid having to download scripts every single time

### ISSUE THREAD

**Issue by matthiaz** [platformsh/source-operations#6]
Below is a script that can install platformshcli but it also uses the cache. 

You can use it like this
```
hooks:
    build: |
        set -e
        bash install_cli_tool.sh
```
and/or

```
source:
    operations:
        do_stuff:
            command: |
                set -e
                bash install_cli_tool.s
```

Script:
```
#!/bin/bash
#install_cli_tool.sh

run() {
    cache_folder="${PLATFORM_CACHE_DIR}/.platformsh"
    cache_file="$cache_folder/bin/platform"
    echo "Cache folder $cache_folder"
    echo "Cache file $cache_file"
    echo "Current folder $(pwd)"
    if [ ! -f ${cache_file} ]; 
    then
        # if we don't have platform cli cached, we need to install it
        install_components
        copy_lib_to_cache
    else
        # if we have platform cli cached, we can just copy it
        copy_lib_from_cache
    fi
}

install_components() {
    curl -sS https://platform.sh/cli/installer | php    
}

copy_lib_to_cache() {
    echo "Copy to cache..."
    cp -Rf $PLATFORM_APP_DIR/.platformsh $PLATFORM_CACHE_DIR
}

copy_lib_from_cache() {
    echo "Copy from cache..."
    cp -Rf $PLATFORM_CACHE_DIR/.platformsh $PLATFORM_APP_DIR
    echo 'export PATH="$PLATFORM_APP_DIR/.platformsh/bin":"$PATH"' >> .environment
}

echo "Installing Platform Cli tool"
run $@
```

We could probably change this script up a bit, so that it can be used in the [default install instructions](https://github.com/platformsh/source-operations#installation). This has huge benefits:
- less build time :hourglass: 
- happier customers :smile: 
- costs us less :moneybag: 
- and is better for our planet :deciduous_tree: 
- more control over when builds will use a new version (platform p:clear-build-cache) :control_knobs:

**Comment by gilzow** [comment]
Apologies for not responding to this sooner. 

Only the `trigger-sopupdate` command uses the platformsh cli tool, and is built to be run on/in multiple scenarios.  We can't be sure that it's running in a Platform.sh environment, or that the temp directory will be accessible from run-to-run (e.g. running in github runner).  Given that, we'd probably need to change 
```
cache_folder="${PLATFORM_CACHE_DIR}/.platformsh"
```
to something like
```
cache_folder="${PLATFORM_CACHE_DIR:-${TMPDIR:-/tmp}}/.platformsh"
```
to ensure we're targeting something that might actually be there. 

Ideally, I'd say we move your sample script into [the docs](https://docs.platform.sh/) or [community site](https://community.platform.sh/) and then add a link to it from the readme for those who want to use the command in a cron job.

FWIW, I did use your idea to help shave some time/bytes from the git clone for the `sop-autoupdate` command which _does_ run on a platform.sh environment.
